[package]
name = "dictation-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
serde = { workspace = true }
serde_json = { workspace = true }

dictation-gui = { path = "../dictation-gui" }
dictation-types = { path = "../dictation-types" }
shellexpand = "3"
vosk = "0.3.1"
cpal = "0.15"
toml = "0.8"
harper-core = "0.68"
whisper-rs = "0.15"
reqwest = { version = "0.12", features = ["blocking"] }
indicatif = "0.17"
zbus = "4.1"

[lib]
name = "dictation_engine"
path = "src/lib.rs"
